### ISSUE TITLE
Error: Cannot find module 'aws4'

### ISSUE THREAD

**Issue by strif** [mattdy/MMM-TeslaFi#30]
The inclusion of the MMM-Teslafi module into my config file breaks my MagicMirror which then loads without any modules on a black screen.

When I try to "npm start", I get the following error:

`pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.18.0 start
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[15.02.2022 13:17.02.243] [LOG]   Starting MagicMirror: v2.18.0
[15.02.2022 13:17.02.279] [LOG]   Loading config ...
[15.02.2022 13:17.02.296] [LOG]   Loading module helpers ...
[15.02.2022 13:17.02.307] [LOG]   No helper found for module: alert.
[15.02.2022 13:17.02.401] [LOG]   Initializing new module helper ...
[15.02.2022 13:17.02.416] [LOG]   Module helper loaded: updatenotification
[15.02.2022 13:17.02.419] [LOG]   No helper found for module: clock.
[15.02.2022 13:17.02.677] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'aws4'
Require stack:
- /home/pi/MagicMirror/node_modules/request/request.js
- /home/pi/MagicMirror/node_modules/request/index.js
- /home/pi/MagicMirror/modules/MMM-TeslaFi/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
[15.02.2022 13:17.02.682] [LOG]   Loading module helpers ...
[15.02.2022 13:17.02.685] [LOG]   No helper found for module: alert.
[15.02.2022 13:17.02.688] [LOG]   Initializing new module helper ...
[15.02.2022 13:17.02.690] [LOG]   Module helper loaded: updatenotification
[15.02.2022 13:17.02.697] [LOG]   No helper found for module: clock.
[15.02.2022 13:17.02.725] [ERROR] App threw an error during load
[15.02.2022 13:17.02.737] [ERROR] Error: Cannot find module 'aws4'
Require stack:
- /home/pi/MagicMirror/node_modules/request/request.js
- /home/pi/MagicMirror/node_modules/request/index.js
- /home/pi/MagicMirror/modules/MMM-TeslaFi/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:10:12)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
[15.02.2022 13:17.02.745] [ERROR] Whoops! There was an uncaught exception...
[15.02.2022 13:17.02.784] [ERROR] Error: Cannot find module 'aws4'
Require stack:
- /home/pi/MagicMirror/node_modules/request/request.js
- /home/pi/MagicMirror/node_modules/request/index.js
- /home/pi/MagicMirror/modules/MMM-TeslaFi/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:10:12)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/node_modules/request/request.js',
    '/home/pi/MagicMirror/node_modules/request/index.js',
    '/home/pi/MagicMirror/modules/MMM-TeslaFi/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[15.02.2022 13:17.02.806] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[15.02.2022 13:17.02.811] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[15.02.2022 13:17.03.608] [LOG]   Launching application.
[12452:0215/131705.049525:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[12475:0215/131705.574120:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
`

Is this still working for everyone?

**Comment by mattdy** [comment]
Thanks for the report. Could you please confirm you've run `npm install` inside the project directory?

**Comment by strif** [comment]
Matt, thank you so much for your prompt follow up.

The npm install runs sucessfuly, but gives me:

`$ npm install

up to date, audited 331 packages in 9s

68 packages are looking for funding
  run `npm fund` for details

8 moderate severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
`


When I try npm audit fix, it gives me:



`pi@raspberrypi:~/MagicMirror $ npm audit fix
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /home/pi/MagicMirror/node_modules/asn1
npm ERR! dest /home/pi/MagicMirror/node_modules/.asn1-n6Us0NZZ
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/home/pi/MagicMirror/node_modules/asn1' -> '/home/pi/MagicMirror/node_modules/.asn1-n6Us0NZZ'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-02-15T14_33_05_806Z-debug-0.log
`

**Comment by mattdy** [comment]
That seems like there may be an error with the installation, could you try deleting the module folder and starting again?

**Comment by strif** [comment]
Hi Matt,

Yes. I tried several times. npm install completes successfully when I'm on the MMM-TeslaFi folder with 8 vilnernabilities, and I get the same error when I run npm start from the route of MagicMirror.



When I try to uninstall and install the module again, I get this error:

`$ sudo npm uninstall MMM-Teslafi
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /home/pi/MagicMirror/node_modules/aws4
npm ERR! dest /home/pi/MagicMirror/node_modules/.aws4-UCiv5nCu
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/home/pi/MagicMirror/node_modules/aws4' -> '/home/pi/MagicMirror/node_modules/.aws4-UCiv5nCu'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-15T15_42_39_196Z-debug-0.log
`

so I had to delete the module's folder, clone and npm install from modules/MMM-TeslaFi

**Comment by mattdy** [comment]
I've just attempted a fresh installation which completed and runs successfully, so I'm afraid this appears to be a problem with your local setup rather than the module itself.

Could you perhaps trying installing using [MMPM](https://github.com/Bee-Mar/mmpm) instead?

**Comment by strif** [comment]
I've installed MMM-TeslaFi via the mmpm installer on a fresh installation of MagicMirror which was installed on the latest version of Raspberry Pi OS.

MagicMirror would not boot up giving me the following error code. Can someone help me find out what's actually wrong by looking at the error message?




`[pi@raspberrypi](mailto:pi@raspberrypi):~/MagicMirror $ npm start

> [magicmirror@2.18.0](mailto:magicmirror@2.18.0) start
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[15.02.2022 20:47.27.777] [LOG]  Starting MagicMirror: v2.18.0
[15.02.2022 20:47.27.790] [LOG]  Loading config ...
[15.02.2022 20:47.27.808] [LOG]  Loading module helpers ...
[15.02.2022 20:47.27.813] [LOG]  No helper found for module: alert.
[15.02.2022 20:47.27.853] [LOG]  Initializing new module helper ...
[15.02.2022 20:47.27.857] [LOG]  Module helper loaded: updatenotification
[15.02.2022 20:47.27.860] [LOG]  No helper found for module: clock.
[15.02.2022 20:47.27.867] [ERROR] WARNING! Could not load config file.
Starting with default configuration. Error found: Error: Cannot find
module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-TeslaFi/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
[15.02.2022 20:47.27.869] [LOG]  Loading module helpers ...
[15.02.2022 20:47.27.872] [LOG]  No helper found for module: alert.
[15.02.2022 20:47.27.874] [LOG]  Initializing new module helper ...
[15.02.2022 20:47.27.876] [LOG]  Module helper loaded: updatenotification
[15.02.2022 20:47.27.878] [LOG]  No helper found for module: clock.
[15.02.2022 20:47.27.884] [ERROR] App threw an error during load
[15.02.2022 20:47.27.890] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-TeslaFi/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Function.Module._resolveFilename
(/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous>
(/home/pi/MagicMirror/modules/MMM-TeslaFi/node_helper.js:13:15)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
[15.02.2022 20:47.27.894] [ERROR] Whoops! There was an uncaught exception...
[15.02.2022 20:47.27.904] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-TeslaFi/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Function.Module._resolveFilename
(/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous>
(/home/pi/MagicMirror/modules/MMM-TeslaFi/node_helper.js:13:15)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js
(node:internal/modules/cjs/loader:1169:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-TeslaFi/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[15.02.2022 20:47.27.908] [ERROR] MagicMirror will not quit, but it
might be a good idea to check why this happened. Maybe no internet
connection?
[15.02.2022 20:47.27.909] [ERROR] If you think this really is an
issue, please open an issue on GitHub:
https://github.com/MichMich/MagicMirror/issues
[15.02.2022 20:47.28.338] [LOG]  Launching application.
[6540:0215/204729.189732:ERROR:viz_main_impl.cc(161)] Exiting GPU
process due to errors during initialization
[6567:0215/204729.505550:ERROR:sandbox_linux.cc(376)]
InitializeSandbox() called with multiple threads in process
gpu-process.`

**Comment by mattdy** [comment]
Apologies - it seems I was mistaken and this was an oversight with the dependency on `request` not being explicitly declared. This works fine on older versions of MM, but not newer installations. If you try re-installing the module from scratch, hopefully it will now work.

**Comment by strif** [comment]
Thank you the installation has worked. MagicMirror boots up, but the TeslaFi doesn't exit from the "Loading ..." view.

I run it as a server with "npm run server" and I see on the developer console that the modules tries to update the DOM without success. 

I get an error "module tries to update the DOM without being displayed"

here is the log when I start my smart mirror with npm start:

[pi@raspberrypi](mailto:pi@raspberrypi):~/MagicMirror $ npm start

> [magicmirror@2.18.0](mailto:magicmirror@2.18.0) start
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[15.02.2022 22:34.38.604] [LOG]  Starting MagicMirror: v2.18.0
[15.02.2022 22:34.38.616] [LOG]  Loading config ...
[15.02.2022 22:34.38.640] [LOG]  Loading module helpers ...
[15.02.2022 22:34.38.649] [LOG]  No helper found for module: alert.
[15.02.2022 22:34.38.693] [LOG]  Initializing new module helper ...
[15.02.2022 22:34.38.696] [LOG]  Module helper loaded: updatenotification
[15.02.2022 22:34.38.698] [LOG]  No helper found for module: clock.
[15.02.2022 22:34.39.124] [LOG]  Initializing new module helper ...
[15.02.2022 22:34.39.129] [LOG]  Module helper loaded: calendar
[15.02.2022 22:34.39.133] [LOG]  No helper found for module: compliments.
[15.02.2022 22:34.39.852] [LOG]  Initializing new module helper ...
[15.02.2022 22:34.39.856] [LOG]  Module helper loaded: MMM-TeslaFi
[15.02.2022 22:34.39.913] [LOG]  Initializing new module helper ...
[15.02.2022 22:34.39.915] [LOG]  Module helper loaded: newsfeed
[15.02.2022 22:34.39.916] [LOG]  All module helpers loaded.
[15.02.2022 22:34.40.110] [LOG]  Starting server on port 8080 ...
[15.02.2022 22:34.40.143] [LOG]  Server started ...
[15.02.2022 22:34.40.146] [LOG]  Connecting socket for: updatenotification
[15.02.2022 22:34.40.148] [LOG]  Starting module helper: updatenotification
[15.02.2022 22:34.40.151] [LOG]  Connecting socket for: calendar
[15.02.2022 22:34.40.152] [LOG]  Starting node helper for: calendar
[15.02.2022 22:34.40.154] [LOG]  Connecting socket for: MMM-TeslaFi
[15.02.2022 22:34.40.158] [LOG]  Connecting socket for: newsfeed
[15.02.2022 22:34.40.160] [LOG]  Starting node helper for: newsfeed
[15.02.2022 22:34.40.160] [LOG]  Sockets connected & modules started ...
[15.02.2022 22:34.40.614] [LOG]  Launching application.
[2782:0215/223447.659461:ERROR:viz_main_impl.cc(161)] Exiting GPU
process due to errors during initialization
[2823:0215/223448.023175:ERROR:sandbox_linux.cc(376)]
InitializeSandbox() called with multiple threads in process
gpu-process.
[15.02.2022 22:34.52.952] [LOG]  Create new calendarfetcher for url:
[http://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics ](http://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics)-
Interval: 300000
[15.02.2022 22:34.53.056] [INFO]  TeslaFi received configuration
[15.02.2022 22:34.53.074] [INFO]  TeslaFi sending request
[15.02.2022 22:34.53.105] [LOG]  Create new newsfetcher for url:
[https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml ](https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml)- Interval:
300000
[15.02.2022 22:34.53.199] [INFO]  Checking git for module: MMM-TeslaFi
[15.02.2022 22:34.53.304] [INFO]  Checking git for module: default
[15.02.2022 22:34.54.142] [INFO]  TeslaFi response was 200
[15.02.2022 22:34.54.145] [INFO]  TeslaFi sending data
[15.02.2022 22:34.56.025] [INFO]  Calendar-Fetcher: Broadcasting 10 events.
[15.02.2022 22:34.56.434] [INFO]  Newsfeed-Fetcher: Broadcasting 65 items

**Comment by mattdy** [comment]
> Thank you the installation has worked. MagicMirror boots up, but the TeslaFi doesn't exit from the "Loading ..." view.
> 
> I run it as a server with "npm run server" and I see on the developer console that the modules tries to update the DOM without success.
> 
> I get an error "module tries to update the DOM without being displayed"

It appears that's a separate issue caused by changes upstream - should hopefully be a simple fix, I've created a separate issue in #31
